# Generated by Django 2.2 on 2021-02-04 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210204_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Criado', 'Criado'), ('Pendente', 'Pendente'), ('Feito', 'Feito')], default='Criado', max_length=20),
        ),
    ]
